core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
]

logmanager/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls import handler404
from django.shortcuts import render

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('branchs/', include('branch.urls')),
    path('trips/', include('trip.urls')),
    path('vehicles/', include('vehicle.urls')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

def custom_page_not_found_view(request, exception):
    return render(request, 'core/404.html', {}, status=404)

def custom_error_view(request):
    return render(request, 'core/500.html', status=500)

handler404 = custom_page_not_found_view
handler500 = custom_error_view

vehicle/urls.py
from django.urls import path

from . import views

app_name = 'vehicle'

urlpatterns = [
    path('', views.vehicles, name='vehicles'),
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.vehicle, name='vehicle'),
    path('<uuid:pk>/update', views.update, name='update'),
    path('<uuid:pk>/delete', views.delete, name='delete'),
]

vehicle/models.py
import uuid

from django.db import models

from account.models import User

class Vehicle(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    model = models.CharField(max_length=255)
    plate = models.CharField(max_length=7)
    year = models.IntegerField(null=True, blank=True)

    date_joined = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.plate

vehicle/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .models import Vehicle

@login_required
def vehicles(request):
    vehicles = Vehicle.objects.all()

    return render(request, 'vehicles/vehicles.html', {
        'vehicles': vehicles
    })

@login_required
def vehicle(request, pk):
    vehicle = Vehicle.objects.get(pk=pk)

    return render(request, 'vehicles/vehicle.html', {
        'vehicle': vehicle
    })

@login_required
def add(request):
    if request.method == 'POST':
        model = request.POST.get('model', '')
        plate = request.POST.get('plate', '')
        year = request.POST.get('year', '')

        if model and plate and year:
            Vehicle.objects.create(model=model, plate=plate, year=year)

            return redirect('/vehicles/')
        else:
            print('Veículo inválido.')

    return render(request, 'vehicles/add.html')

@login_required
def update(request, pk):
    vehicle = Vehicle.objects.get(pk=pk)
    
    if request.method == 'POST':
        model = request.POST.get('model', '')
        plate = request.POST.get('plate', '')
        year = request.POST.get('year', '')

        print('metódo post')

        if model and plate and year:
            vehicle.model = model
            vehicle.plate = plate
            vehicle.year = year
            vehicle.save()

            print('tudo ok')

            return redirect('/vehicles/')
        else:
            print('Alteração inválida')

    return render(request, 'vehicles/update.html', {
        'vehicle': vehicle
    })

@login_required
def delete(request, pk):
    vehicle = Vehicle.objects.get(pk=pk)
    vehicle.delete()

    return redirect('/vehicles/')

vehicle/templates/vehicles/add.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="max-w-xl mx-auto py-8 bg-slate-400 text-center">
        <h1 class="text-2xl text-slate-800">Adicionar Veículo</h1>

        <form class="mt-6 px-8 space-y-4" method="post" action=".">
            {% csrf_token %}
            <div>
                <label class="text-slate-800">Modelo:</label>
                <input name="model" type="text" class="w-full py-4 px-6 bg-slate-300 text-slate-800">
            </div>
            
            <div>
                <label class="text-slate-800">Placa:</label>
                <input name="plate" type="text" class="w-full py-4 px-6 bg-slate-300 text-slate-800">
            </div>

            <div>
                <label class="text-slate-800">Ano:</label>
                <input name="year" type="text" class="w-full py-4 px-6 bg-slate-300 text-slate-800">
            </div>

            <div>
                <button class="py-4 px-8 bg-slate-600 text-slate-300">Adicionar</button>
            </div>
        </form>
    </div>
{% endblock %}

vehicle/templates/vehicles/update.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="max-w-xl mx-auto py-8 bg-slate-400 text-center">
        <h1 class="text-2xl text-slate-800">Editar Veículo</h1>

        <form class="mt-6 px-8 space-y-4" method="post" action=".">
            {% csrf_token %}
            <div>
                <label class="text-slate-800">Modelo:</label>
                <input name="model" type="text" value="{{ vehicle.model }}" class="w-full py-4 px-6 bg-slate-300 text-slate-800">
            </div>
            
            <div>
                <label class="text-slate-800">Placa:</label>
                <input name="plate" type="text" value="{{ vehicle.plate }}" class="w-full py-4 px-6 bg-slate-300 text-slate-800">
            </div>

            <div>
                <label class="text-slate-800">Ano:</label>
                <input name="year" type="text" value="{{ vehicle.year }}" class="w-full py-4 px-6 bg-slate-300 text-slate-800">
            </div>

            <div>
                <button type="submit" class="py-4 px-8 bg-slate-600 text-slate-300">Salvar</button>
            </div>
        </form>
    </div>
{% endblock %}

vehicle/templates/vehicles/vehicle.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="text-2xl text-slate-800">{{ vehicle.model }}</h1>


    <div class="mt-6 grid grid-cols-1 md:grid-cols-4 md:grid-rows-4 gap-4">

        <p class="text-sm text-slate-800">
            <strong>Placa:</strong> {{ vehicle.plate }}
        </p>
        <p class="text-sm text-slate-800">
            <strong>Ano:</strong> {{ vehicle.year }}
        </p>
        <div>
            <a href="{% url 'vehicle:update' vehicle.id %}" class="py-2 mr-5 px-4 md:py-4 md:px-8 bg-green-800 text-slate-300">Editar</a> 
            <a href="{% url 'vehicle:delete' vehicle.id %}" class="py-2 px-4 md:py-4 md:px-8 bg-red-800 text-slate-300">Deletar</a> 
        </div>
              
    </div>
{% endblock %}

vehicle/templates/vehicles/vehicles.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="text-2xl text-slate-800">Veículos</h1>

    <a href="{% url 'vehicle:add' %}" class="py-4 px-8 mt-6 bg-slate-600 text-slate-300 inline-block">Adicionar veículo</a>

    <div class="mt-6 grid grid-cols-1 md:grid-cols-4 md:grid-rows-4 gap-4">
        {% for vehicle in vehicles %}
            <div class="py-6 px-6 bg-slate-400">
                <a href="{% url 'vehicle:vehicle' vehicle.id %}">
                    <h2 class="mb-4 text-xl">{{ vehicle.model }}</h2>

                    <p class="text-sm text-slate-800">
                        <strong>Placa:</strong> {{ vehicle.plate }}
                    </p>
                    <p class="text-sm text-slate-800">
                        <strong>Ano:</strong> {{ vehicle.year }}
                    </p>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}