account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

branch/urls.py
from django.urls import path

from . import views

app_name = 'branch'

urlpatterns = [
    path('', views.branchs, name='branchs'),
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.branch, name='branch'),
    path('<uuid:pk>/update', views.update, name='update'),
    path('<uuid:pk>/delete', views.delete, name='delete'),
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
]

logmanager/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls import handler404
from django.shortcuts import render

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('branchs/', include('branch.urls')),
    path('trips/', include('trip.urls')),
    path('vehicles/', include('vehicle.urls')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

def custom_page_not_found_view(request, exception):
    return render(request, 'core/404.html', {}, status=404)

def custom_error_view(request):
    return render(request, 'core/500.html', status=500)

handler404 = custom_page_not_found_view
handler500 = custom_error_view

trip/urls.py
from django.urls import path

from . import views

app_name = 'trip'

urlpatterns = [
    path('', views.trips, name='trips'),
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.trip, name='trip'),
    path('<uuid:pk>/completed', views.completed, name='completed'),
    path('<uuid:pk>/update', views.update, name='update'),
    path('<uuid:pk>/delete', views.delete, name='delete'),
]

vehicle/urls.py
from django.urls import path

from . import views

app_name = 'vehicle'

urlpatterns = [
    path('', views.vehicles, name='vehicles'),
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.vehicle, name='vehicle'),
    path('<uuid:pk>/update', views.update, name='update'),
    path('<uuid:pk>/delete', views.delete, name='delete'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'core/index.html')

def about(request):
    return render(request, 'core/about.html')

core/templates/core/about.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="text-3xl">Sobre</h1>

    <div class="mt-6 space-y-6">
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat ratione, id mollitia aspernatur quos illo reprehenderit minus sapiente neque maiores quaerat vitae fugiat magni esse nisi aut aperiam accusantium in!
        </p>

        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat ratione, id mollitia aspernatur quos illo reprehenderit minus sapiente neque maiores quaerat vitae fugiat magni esse nisi aut aperiam accusantium in!
        </p>
    </div>
{% endblock %}

core/templates/core/base.html
<!doctype html>
<html>
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body class="bg-slate-200 min-h-screen flex flex-col">
        <nav class="py-6 px-4 md:px-20 flex items-center justify-between bg-slate-800">
            <h1 class="text-lg md:text-xl text-slate-300"><a href="{% url 'core:index' %}">Log Manager</a></h1>
            <div class="space-x-2 md:space-x-4 flex flex-col md:flex-row items-center">
                <a href="{% url 'core:about' %}" class="text-slate-300 py-2 md:py-0">Sobre</a>

                {% if request.user.is_authenticated %}
                    <p class="text-slate-300">Olá, {{ user.name }}</p>
                    <a href="{% url 'account:logout' %}" class="text-slate-300 py-2 md:py-0">Sair</a>
                    <a href="{% url 'branch:branchs' %}" class="py-2 px-4 md:py-4 md:px-8 bg-slate-200 text-slate-800">Filiais</a>
                    <a href="{% url 'vehicle:vehicles' %}" class="py-2 px-4 md:py-4 md:px-8 bg-slate-600 text-slate-300">Veículos</a>
                    <a href="{% url 'trip:trips' %}" class="py-2 px-4 md:py-4 md:px-8 bg-slate-400 text-slate-800">Viagens</a>                    
                {% else %}
                    <a href="{% url 'account:login' %}" class="py-2 px-4 md:py-4 md:px-8 bg-slate-400 text-slate-800">Login</a>
                    <a href="{% url 'account:signup' %}" class="py-2 px-4 md:py-4 md:px-8 bg-slate-600 text-slate-300">Cadastre-se</a>
                {% endif %}
            </div>
        </nav>

        <main class="py-6 px-8 md:px-20 flex-grow">
            {% block content %}
            {% endblock %}
        </main>

        <footer class="py-8 px-4 md:px-8 bg-slate-950 text-center">
            <p class="text-slate-300">© 2024 Eduardo Zago - All rights reserved.</p>
        </footer>
    </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="text-2xl text-slate-800">Bem vindo(a) ao Log Manager</h1>
{% endblock %}