branch/urls.py
from django.urls import path

from . import views

app_name = 'branch'

urlpatterns = [
    path('', views.branchs, name='branchs'),
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.branch, name='branch'),
    path('<uuid:pk>/update', views.update, name='update'),
    path('<uuid:pk>/delete', views.delete, name='delete'),
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
]

logmanager/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls import handler404
from django.shortcuts import render

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('branchs/', include('branch.urls')),
    path('trips/', include('trip.urls')),
    path('vehicles/', include('vehicle.urls')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

def custom_page_not_found_view(request, exception):
    return render(request, 'core/404.html', {}, status=404)

def custom_error_view(request):
    return render(request, 'core/500.html', status=500)

handler404 = custom_page_not_found_view
handler500 = custom_error_view

branch/models.py
import uuid

from django.db import models

class Branch(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)

    def __str__(self):
        return self.name 

branch/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .models import Branch

@login_required
def branchs(request):
    branchs = Branch.objects.all()

    return render(request, 'branchs/branchs.html', {
        'branchs': branchs
    })

@login_required
def branch(request, pk):
    branch = Branch.objects.get(pk=pk)

    return render(request, 'branchs/branch.html', {
        'branch': branch
    })

@login_required
def add(request):
    if request.method == 'POST':
        name = request.POST.get('name', '')
        address = request.POST.get('address', '')

        if name and address:
            Branch.objects.create(name=name, address=address)

            return redirect('/branchs/')
        else:
            print('Filial inválida.')

    return render(request, 'branchs/add.html')

@login_required
def update(request, pk):
    print('Método HTTP:', request.method) 
    branch = Branch.objects.get(pk=pk)
    
    if request.method == 'POST':
        name = request.POST.get('name', '')
        address = request.POST.get('address', '')

        if name and address:
            branch.name = name
            branch.address = address
            branch.save()
            print('tudo ok')
            return redirect('/branchs/')
        else:
            print('Alteração inválida')

    return render(request, 'branchs/update.html', {
        'branch': branch
    })

@login_required
def delete(request, pk):
    branch = Branch.objects.get(pk=pk)
    branch.delete()

    return redirect('/branchs/')

branch/templates/branchs/add.html
{% extends 'core/base.html' %}

{% block content %}
<div class="max-w-xl mx-auto py-8 bg-slate-400 text-center">
    <h1 class="text-2xl text-slate-800">Nova Filial</h1>

    <form class="mt-6 px-8 space-y-4" method="post" action=".">
        {% csrf_token %}
        <div>
            <label class="text-slate-800">Nome:</label>
            <input name="name" type="text" class="w-full py-4 px-6 bg-slate-300 text-slate-800">
        </div>
        
        <div>
            <label class="text-slate-800">Endereço:</label>
            <input name="address" type="text" class="w-full py-4 px-6 bg-slate-300 text-slate-800">
        </div>
        <div>
            <button class="py-4 px-8 bg-slate-600 text-slate-300">Adicionar</button>
        </div>
    </form>
</div>
{% endblock %}

branch/templates/branchs/branch.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="text-2xl text-slate-800">{{ branch.name }}</h1>


    <div class="mt-6 grid grid-cols-1 md:grid-cols-4 md:grid-rows-4 gap-4">

        <p class="text-sm text-slate-800">
            <strong>Endereço:</strong> {{ branch.address }}
        </p>
        <div>
            <a href="{% url 'branch:update' branch.id %}" class="py-2 mr-5 px-4 md:py-4 md:px-8 bg-green-800 text-slate-300">Editar</a> 
            <a href="{% url 'branch:delete' branch.id %}" class="py-2 px-4 md:py-4 md:px-8 bg-red-800 text-slate-300">Deletar</a> 
        </div>
    </div>
{% endblock %}

branch/templates/branchs/branchs.html
{% extends 'core/base.html' %}

{% block content %}
<h1 class="text-2xl text-slate-800">Filiais</h1>

    <a href="{% url 'branch:add' %}" class="py-4 px-8 mt-6 bg-slate-600 text-slate-300 inline-block">Nova Filial</a>

    <div class="mt-6 grid grid-cols-1 md:grid-cols-4 md:grid-rows-4 gap-4">
        {% for branch in branchs %}
            <div class="py-6 px-6 bg-slate-400">
                <a href="{% url 'branch:branch' branch.id %}">
                    <h2 class="mb-4 text-xl">{{ branch.name }}</h2>

                    <p class="text-sm text-slate-800">
                        <strong>Endereço:</strong> {{ branch.address }}
                    </p>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

branch/templates/branchs/update.html
{% extends 'core/base.html' %}

{% block content %}
<div class="max-w-xl mx-auto py-8 bg-slate-400 text-center">
    <h1 class="text-2xl text-slate-800">Editar Filial</h1>

    <form class="mt-6 px-8 space-y-4" method="post" action=".">
        {% csrf_token %}
        <div>
            <label class="text-slate-800">Nome:</label>
            <input name="name" type="text" value="{{ branch.name }}" class="w-full py-4 px-6 bg-slate-300 text-slate-800">
        </div>
        
        <div>
            <label class="text-slate-800">Endereço:</label>
            <input name="address" type="text" value="{{ branch.address }}" class="w-full py-4 px-6 bg-slate-300 text-slate-800">
        </div>
        <div>
            <button class="py-4 px-8 bg-slate-600 text-slate-300">Salvar</button>
        </div>
    </form>
</div>
{% endblock %}