core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
]

logmanager/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls import handler404
from django.shortcuts import render

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('branchs/', include('branch.urls')),
    path('trips/', include('trip.urls')),
    path('vehicles/', include('vehicle.urls')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

def custom_page_not_found_view(request, exception):
    return render(request, 'core/404.html', {}, status=404)

def custom_error_view(request):
    return render(request, 'core/500.html', status=500)

handler404 = custom_page_not_found_view
handler500 = custom_error_view

trip/urls.py
from django.urls import path

from . import views

app_name = 'trip'

urlpatterns = [
    path('', views.trips, name='trips'),
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.trip, name='trip'),
    path('<uuid:pk>/completed', views.completed, name='completed'),
    path('<uuid:pk>/update', views.update, name='update'),
    path('<uuid:pk>/delete', views.delete, name='delete'),
]

trip/models.py
import uuid

from django.db import models

from vehicle.models import Vehicle
from branch.models import Branch

class Trip(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    origin = models.ForeignKey(Branch, on_delete=models.CASCADE, related_name='trip_origin')
    destiny = models.ForeignKey(Branch, on_delete=models.CASCADE, related_name='trip_destiny')

    date_joined = models.DateTimeField(auto_now_add=True)

    completed = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.vehicle.name} from {self.origin} to {self.destiny}'

trip/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .models import Trip, Vehicle, Branch

@login_required
def trips(request):
    trips = Trip.objects.all()

    return render(request, 'trips/trips.html', {
        'trips': trips
    })

@login_required
def trip(request, pk):
    trip = Trip.objects.get(pk=pk)

    return render(request, 'trips/trip.html', {
        'trip': trip
    })

@login_required
def add(request):
    if request.method == 'POST':
        vehicle_id = request.POST.get('vehicle', '')
        origin_id = request.POST.get('origin', '')
        destiny_id = request.POST.get('destiny', '')

        vehicle = Vehicle.objects.get(pk=vehicle_id)
        origin = Branch.objects.get(pk=origin_id)
        destiny = Branch.objects.get(pk=destiny_id)

        if vehicle and origin and destiny:
            Trip.objects.create(vehicle=vehicle, origin=origin, destiny=destiny)

            return redirect('/trips/')
        else:
            print('Viagem inválida.')

    vehicles = Vehicle.objects.all()
    branches = Branch.objects.all()

    return render(request, 'trips/add.html', {
        'vehicles': vehicles,
        'branches': branches,
    })

@login_required
def completed(request, pk):
    trip = Trip.objects.get(pk=pk)

    trip.completed = True
    trip.save()

    return redirect('/trips/')

@login_required
def update(request, pk):
    trip = Trip.objects.get(pk=pk)

    if request.method == 'POST':
        vehicle_id = request.POST.get('vehicle', '')
        origin_id = request.POST.get('origin', '')
        destiny_id = request.POST.get('destiny', '')

        trip.vehicle_id = vehicle_id
        trip.origin_id = origin_id
        trip.destiny_id = destiny_id

        if trip.vehicle_id and trip.origin_id and trip.destiny_id:
            trip.save()

            return redirect('/trips/', pk=trip.pk)
        else:
            print('Alteração inválida.')

    vehicles = Vehicle.objects.all()
    branches = Branch.objects.all()

    return render(request, 'trips/update.html', {
        'vehicles': vehicles,
        'branches': branches,
        'trip': trip,
    })

    

@login_required
def delete(request, pk):
    trip = Trip.objects.get(pk=pk)
    trip.delete()

    return redirect('/trips/')

trip/templates/trips/add.html
{% extends 'core/base.html' %}

{% block content %}
<div class="max-w-xl mx-auto py-8 bg-slate-400 text-center">
    <h1 class="text-2xl text-slate-800">Nova Viagem</h1>

    <form class="mt-6 px-8 space-y-4" method="post" action=".">
        {% csrf_token %}
        <div>
            <label class="text-slate-800">Veículo:</label>
            <select name="vehicle" type="text" class="w-full py-4 px-6 bg-slate-300 text-slate-800">
                {% for vehicle in vehicles %}
                    <option value="{{ vehicle.id }}">{{ vehicle.model }} - {{ vehicle.plate }}</option>
                {% endfor %}
            </select>
        </div>
        
        <div>
            <label class="text-slate-800">Origem:</label>
            <select name="origin" type="text" class="w-full py-4 px-6 bg-slate-300 text-slate-800">
                {% for branch in branches %}
                    <option value="{{ branch.id }}">{{ branch.name }}</option>
                {% endfor %}
            </select>
        </div>

        <div>
            <label class="text-slate-800">Destino:</label>
            <select name="destiny" type="text" class="w-full py-4 px-6 bg-slate-300 text-slate-800">
                {% for branch in branches %}
                    <option value="{{ branch.id }}">{{ branch.name }}</option>
                {% endfor %}
            </select>
        </div>

        <div>
            <button class="py-4 px-8 bg-slate-600 text-slate-300">Adicionar</button>
        </div>
    </form>
</div>
{% endblock %}

trip/templates/trips/trip.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="text-2xl text-slate-800">{{ trip.origin.name }} para {{ trip.destiny.name }}</h1>

    <div class="mt-6 grid grid-cols-1 md:grid-cols-4 md:grid-rows-4 gap-4">

        <p class="text-sm text-slate-800">
            <strong>Veículo:</strong> {{ trip.vehicle.model }} - {{ trip.vehicle }}
        </p>
        <p class="text-sm text-slate-800">
            <strong>Origem:</strong> {{ trip.origin }}
        </p>
        <p class="text-sm text-slate-800">
            <strong>Destino:</strong> {{ trip.destiny }}
        </p>
        <p class="text-sm text-slate-800">
            <strong>Status:</strong> 
                {% if not trip.completed %}
                    Em andamento
                {% else %}
                    Concluída
                {% endif %}
        </p>
        {% if not trip.completed %}
            <a href="{% url 'trip:completed' trip.id %}" class="py-2 mr-5 px-4 md:py-4 md:px-8 bg-emerald-500 text-slate-800">Marcar como concluída</a> 
        {% endif %}
        <a href="{% url 'trip:update' trip.id %}" class="py-2 mr-5 px-4 md:py-4 md:px-8 bg-green-800 text-slate-300">Editar</a> 
        <a href="{% url 'trip:delete' trip.id %}" class="py-2 px-4 md:py-4 md:px-8 bg-red-800 text-slate-300">Deletar</a> 
    </div>
{% endblock %}

trip/templates/trips/trips.html
{% extends 'core/base.html' %}

{% block content %}
<h1 class="text-2xl text-slate-800">Viagens</h1>

<a href="{% url 'trip:add' %}" class="py-4 px-8 mt-6 bg-slate-600 text-slate-300 inline-block">Adicionar viagem</a>

<div class="mt-6 grid grid-cols-1 md:grid-cols-4 md:grid-rows-4 gap-4">
    {% for trip in trips %}
        <div class="py-6 px-6 bg-slate-400">
            <a href="{% url 'trip:trip' trip.id %}">
                <h2 class="mb-4 text-xl">{{ trip.origin.name }} para {{ trip.destiny.name }}</h2>

                <p class="text-sm text-slate-800">
                    <strong>Veículo:</strong> {{ trip.vehicle.model }} - {{ trip.vehicle }}
                </p>
                <p class="text-sm text-slate-800">
                    <strong>Origem:</strong> {{ trip.origin }}
                </p>
                <p class="text-sm text-slate-800">
                    <strong>Destino:</strong> {{ trip.destiny }}
                </p>
                <p class="text-sm text-slate-800">
                    <strong>Status:</strong> 
                    {% if not trip.completed %}
                        Em andamento
                    {% else %}
                        Concluída
                    {% endif %}
                </p>
            </a>
        </div>
    {% endfor %}
</div>
{% endblock %}

trip/templates/trips/update.html
{% extends 'core/base.html' %}

{% block content %}
<div class="max-w-xl mx-auto py-8 bg-slate-400 text-center">
    <h1 class="text-2xl text-slate-800">Editar Viagem</h1>

    <form class="mt-6 px-8 space-y-4" method="post" action=".">
        {% csrf_token %}
        <div>
            <label for="vehicle" class="text-slate-800">Veículo:</label>
            <select id="vehicle" name="vehicle" type="text" class="w-full py-4 px-6 bg-slate-300 text-slate-800">
                {% for vehicle in vehicles %}
                    <option value="{{ vehicle.id }}" {% if vehicle.id == trip.vehicle_id %}selected{% endif %}>{{ vehicle.model }} - {{ vehicle.plate }}</option>
                {% endfor %}
            </select>
        </div>
        
        <div>
            <label for="origin" class="text-slate-800">Origem:</label>
            <select id="origin" name="origin" type="text" class="w-full py-4 px-6 bg-slate-300 text-slate-800">
                {% for branch in branches %}
                    <option value="{{ branch.id }}" {% if branch.id == trip.origin_id %}selected{% endif %}>{{ branch.name }}</option>
                {% endfor %}
            </select>
        </div>

        <div>
            <label for="destiny" class="text-slate-800">Destino:</label>
            <select id="destiny" name="destiny" type="text" class="w-full py-4 px-6 bg-slate-300 text-slate-800">
                {% for branch in branches %}
                    <option value="{{ branch.id }}" {% if branch.id == trip.destiny_id %}selected{% endif %}>{{ branch.name }}</option>
                {% endfor %}
            </select>
        </div>

        <div>
            <button class="py-4 px-8 bg-slate-600 text-slate-300">Salvar</button>
        </div>
    </form>
</div>
{% endblock %}